.TH ERRNO "1" "Feb 2013" "MegaCoder.com" "User Commands"
.SH NAME
xmms-osd \- display XMMS song information changes via an OSD
.SH SYNOPSIS
.B xmms-osd
[\fB\-c\fR \fIcolor\fP]
[\fB\-f\fR \fIfont\fP]
[\fB\-H\fR \fIoffset\fP]
[\fB\-V\fR \fIoffset\fP]
[\fB\-h\fR \fIhpos\fP]
[\fB\-v\fR \fIvpos\fP]
.SH DESCRIPTION
.PP
If given a number, displays the associated \fIxmms-osd\fP value and a descriptive comment.
If given a name, does the same.
.TP
[\fB\-c\fR \fIcolor\fP]
set text notification color; use either the color name or the hex
representation
.TP
[\fB\-f\fR \fIfont\fP]
set the font using the old xlsfont(1) of the name.
.TP
[\fB\-H\fR \fIdelta\fP]
provide a pixel offset from the horizontal position.
.TP
[\fB\-V\fR \fIdelta\fP]
provide a pixel offset from the vertical position.
.TP
[\fB\-h\fR \fIhpos\fP]
set horizontal position:
\fIleft\fP
\fImiddle\fP
\fIright\fP
.TP
[\fB\-v\fR \fIvpos\fP]
set vertical position:
\fItop\fP
\fIcenter\fP
\fIbottom\fP
.SH AUTHOR
Written by Tommy Reynolds <Tommy.Reynolds@MegaCoder.com>
.SH COPYRIGHT
Copyright \(co 2013-2014 Tommy Reynolds; all rights reserved; international copyright secured.
.PP
This code is licensed under the GPL v2, and no other.
