.TH ERRNO "1" "Sep 2013" "MegaCoder.com" "User Commands"
.SH NAME
xmms-osd \- display XMMS song information changes via an OSD
.SH SYNOPSIS
.B xmms-osd
[\fB\-c\fR \fIcolor\fP]
[\fB\-X\fR \fIoffset\fP]
[\fB\-Y\fR \fIoffset\fP]
[\fB\-x\fR \fIhpos\fP]
[\fB\-y\fR \fIvpos\fP]
.SH DESCRIPTION
.PP
If given a number, displays the associated \fIxmms-osd\fP value and a descriptive comment.
If given a name, does the same.
.TP
[\fB\-c\fR \fIcolor\fP]
.TP
[\fB\-X\fR \fIoffset\fP]
.TP
[\fB\-Y\fR \fIoffset\fP]
.TP
[\fB\-x\fR \fIhpos\fP]
.TP
[\fB\-y\fR \fIvpos\fP]
.SH AUTHOR
Written by Tommy Reynolds <Tommy.Reynolds@MegaCoder.com>
.SH COPYRIGHT
Copyright \(co 2013 Tommy Reynolds; all rights reserved; international copyright secured.
.PP
This code is licensed under the GPL v2, and no other.
.SH "SEE ALSO"
.PP
\fIxmms-osd(\fP3\fI)\fP
